export const FRAMES_PER_REAL_SECOND = 60;
export const SIMULATION_STEPS_PER_REAL_SECOND = 120;
export const GAME_SECONDS_PER_REAL_SECONDS = 1;


export const SIMULATION_STEPS_PER_FRAME = Math.round(SIMULATION_STEPS_PER_REAL_SECOND / FRAMES_PER_REAL_SECOND);
export const FRAMES_PER_REAL_MS = FRAMES_PER_REAL_SECOND / 1000;
export const GAME_SECONDS_PER_FRAME = 1 / FRAMES_PER_REAL_SECOND * GAME_SECONDS_PER_REAL_SECONDS;
export const GAME_MS_PER_FRAME = 1000 / FRAMES_PER_REAL_SECOND * GAME_SECONDS_PER_REAL_SECONDS;
export const GAME_SECONDS_PER_SIMULATION_STEP = GAME_SECONDS_PER_FRAME / SIMULATION_STEPS_PER_FRAME;


export const MAX_NETWORK_INTERPOLATION_SPAN_REAL_SECONDS = 2;
